package page

import (
	"fmt"
	"io"
	"strconv"

	"github.com/Tzomily-Anvar/argus/internal/sprint"
)

// The headline: a line saying when this was generated, the capacity
// review badge, and the totals as a list. The dashboard shows these as
// tiles; a page reads them as a list, and the list keeps the same
// hints beneath the same numbers.
var summaryTmpl = tmpl("summary", `<h2>{{.Heading}}</h2>
<p><em>{{.Generated}}</em> <ac:structured-macro ac:name="status"><ac:parameter ac:name="title">{{.Review}}</ac:parameter></ac:structured-macro></p>
<ul>
{{range .Items}}<li>{{.}}</li>
{{end}}</ul>
`)

type summaryView struct {
	Heading   string
	Generated string
	Review    string
	Items     []string
}

func renderSummary(w io.Writer, rep sprint.Report, in Inputs, _ map[string]bool) error {
	s := rep.Summary
	v := summaryView{
		Heading:   headings[SectionSummary],
		Generated: generatedLine(rep, in),
		Review:    reviewBadge(rep.CapacityReview),
	}

	v.Items = append(v.Items, "Baseline: "+num(s.BaselineTotal)+" pts, what the measured people would deliver at full availability")
	v.Items = append(v.Items, "Capacity: "+num(s.CapacityTotal)+" pts, baseline less planned leave")
	if s.UnplannedDaysOff > 0 {
		// Unplanned absence does not shrink capacity, so a shortfall
		// stays visible as a shortfall; it is named here as the part of
		// the gap nobody could plan around.
		v.Items = append(v.Items, fmt.Sprintf("Unplanned absence: %s days, accounting for %s pts of the shortfall",
			num(s.UnplannedDaysOff), num(s.ShortfallFromAbsence)))
	}
	delivered := "Delivered: " + num(s.DeliveredTotal) + " pts, tasks and bugs finished here"
	if s.FinishedFromEarlier > 0 {
		delivered += " · " + strconv.Itoa(s.FinishedFromEarlier) + " started in an earlier sprint"
	}
	v.Items = append(v.Items, delivered)
	if s.UnattributedPoints > 0 {
		v.Items = append(v.Items, "Delivered by nobody in particular: "+num(s.UnattributedPoints)+
			" pts, unassigned with no time logged, so the per-person figures fall short of the total by this much")
	}
	v.Items = append(v.Items, "Carried over: "+plural(s.CarriedOver, "ticket", "tickets")+" still open at close")
	v.Items = append(v.Items, "Never started: "+plural(s.NeverStarted, "ticket", "tickets")+" untouched all sprint")
	if s.PriorPointsDeducted != 0 {
		v.Items = append(v.Items, "Handed back to earlier sprints: "+num(s.PriorPointsDeducted)+
			" pts they were already credited for")
	}
	return summaryTmpl.Execute(w, v)
}

// generatedLine says who made this and when, and whether the sprint was
// still running. A live page and a closed one read differently: one is
// a snapshot that will move, the other is the record.
func generatedLine(rep sprint.Report, in Inputs) string {
	at := in.GeneratedAt
	if at.IsZero() {
		at = rep.GeneratedAt
	}
	who := "Argus"
	if in.ToolVersion != "" {
		who += " " + in.ToolVersion
	}
	state := "live"
	if rep.Sprint.State == "closed" {
		state = "closed"
	}
	return "Generated by " + who + " on " + day(at) + " · " + state
}

// reviewBadge is the capacity review as one short phrase. Three states,
// not two: a sprint with nobody away and a sprint nobody has filled in
// both have an empty capacity table, and reading the second as the
// first turns a gap into a claim.
func reviewBadge(r sprint.CapacityReview) string {
	switch r.State {
	case sprint.ReviewNoAdjustments:
		return "Capacity: nobody was away"
	case sprint.ReviewAdjusted:
		return "Capacity: " + plural(r.Adjusted, "person", "people") + " away"
	default:
		return "Capacity not reviewed"
	}
}

// Say/do by count, with the counts beneath the ratio so the percentage
// can be checked rather than believed.
var sayDoTmpl = tmpl("saydo", `<h2>{{.Heading}}</h2>
<table><tbody>
<tr><th>Promised</th><th>Injected</th><th>Delivered</th><th>Say/do</th></tr>
<tr><td>{{.Promised}}</td><td>{{.Injected}}</td><td>{{.Delivered}}</td><td>{{.Ratio}}</td></tr>
</tbody></table>
<p>{{.Counts}}</p>
`)

type sayDoView struct {
	Heading                       string
	Promised, Injected, Delivered int
	Ratio, Counts                 string
}

func renderSayDo(w io.Writer, rep sprint.Report, _ Inputs, _ map[string]bool) error {
	s := rep.Summary
	v := sayDoView{
		Heading:   headings[SectionSayDo],
		Promised:  s.Promised,
		Injected:  s.Injected,
		Delivered: s.Completed,
		Ratio:     "—",
	}
	asked := s.Promised + s.Injected
	if asked > 0 {
		v.Ratio = pct(float64(s.Completed) / float64(asked))
	}
	v.Counts = fmt.Sprintf("%d/%d (%d injected)", s.Completed, asked, s.Injected)
	return sayDoTmpl.Execute(w, v)
}
